// @/content/gallery.content.ts
import { GalleryItem } from '@/types/portfolio.types';

export const galleryData: GalleryItem[] = [
  {
    id: 'gal-01',
    title: 'Stage Lighting Geometry',
    category: 'Events',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'landscape',
    date: '2025-03-15',
    location: 'KCT Auditorium',
    cameraGear: 'Sony Cinema Line • 85mm f/1.8',
    caption: 'I framed laser lighting structures during the cultural evening concert.',
  },
  {
    id: 'gal-02',
    title: 'Camera Rig on Location',
    category: 'Cinematography',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'portrait',
    date: '2025-04-10',
    location: 'Studio Set',
    cameraGear: 'Full Frame Rig • Matte Box',
    caption: 'My primary cinema rig ready for a commercial scene.',
  },
  {
    id: 'gal-03',
    title: 'KCT Quadrangle Silhouette',
    category: 'Campus',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'landscape',
    date: '2024-10-12',
    location: 'KCT Campus, Coimbatore',
    cameraGear: '35mm Prime',
    caption: 'I captured late afternoon sun flares illuminating the college administrative architecture.',
  },
  {
    id: 'gal-04',
    title: 'Editing Timeline Detail',
    category: 'Editing',
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'landscape',
    date: '2025-02-18',
    location: 'Editing Workstation',
    cameraGear: 'Adobe Premiere Pro',
    caption: 'Color-coded timeline sequences for a multi-cam event edit.',
  },
  {
    id: 'gal-05',
    title: 'Mountain Fog Lens Flare',
    category: 'Photography',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'square',
    date: '2024-11-04',
    location: 'Valparai Hills',
    cameraGear: '50mm Prime',
    caption: 'I captured atmospheric mist rolling over tea estate hills.',
  },
];
