// @/content/skills.content.ts
import { SkillItem } from '@/types/portfolio.types';

export const skillsData: SkillItem[] = [
  // Creative Skills & Software
  {
    id: 'video-editing',
    name: 'Video Editing',
    category: 'Creative Skills',
    level: 92,
    levelLabel: 'Expert',
    iconName: 'Video',
    description: 'I craft seamless narratives, pacing, rhythm, and audio synchronization for over 50+ event coverage films and commercial projects.',
    isFeatured: true,
  },
  {
    id: 'cinematography',
    name: 'Cinematography',
    category: 'Creative Skills',
    level: 88,
    levelLabel: 'Advanced',
    iconName: 'Camera',
    description: 'I plan camera movement, framing, lighting geometry, and visual composition for narrative short films and campus coverages.',
    isFeatured: true,
  },
  {
    id: 'premiere-pro',
    name: 'Adobe Premiere Pro',
    category: 'Software & Tools',
    level: 90,
    levelLabel: 'Expert',
    iconName: 'Film',
    description: 'My primary editing workstation for multi-cam timelines, proxy workflows, keyframe sound design, and color pipelines.',
    isFeatured: true,
  },
  {
    id: 'davinci-resolve',
    name: 'DaVinci Resolve',
    category: 'Software & Tools',
    level: 85,
    levelLabel: 'Advanced',
    iconName: 'Sliders',
    description: 'I use DaVinci for precision color grading, node-based LUT calibration, shot matching, and cinema export deliverables.',
    isFeatured: true,
  },
  {
    id: 'lightroom',
    name: 'Adobe Lightroom',
    category: 'Software & Tools',
    level: 85,
    levelLabel: 'Advanced',
    iconName: 'Image',
    description: 'I process color balances, highlight retention, and tone curves for photography stills and event coverages.',
  },

  // Programming & Software Engineering
  {
    id: 'cpp',
    name: 'C++ & Data Structures',
    category: 'Programming Skills',
    level: 86,
    levelLabel: 'Advanced',
    iconName: 'Code2',
    description: 'I write clean object-oriented code, memory management routines, and algorithmic problem-solving routines for my CS coursework.',
    isFeatured: true,
  },
  {
    id: 'typescript-javascript',
    name: 'TypeScript & JavaScript',
    category: 'Programming Skills',
    level: 88,
    levelLabel: 'Advanced',
    iconName: 'FileCode',
    description: 'I engineer strongly-typed web architectures, custom hooks, and dynamic component systems using React and Next.js.',
    isFeatured: true,
  },
  {
    id: 'git-github',
    name: 'Git & GitHub',
    category: 'Software & Tools',
    level: 90,
    levelLabel: 'Expert',
    iconName: 'GitBranch',
    description: 'I manage code repositories, feature branching, release tagging, and collaborative commits.',
    isFeatured: true,
  },
  {
    id: 'vscode',
    name: 'VS Code',
    category: 'Software & Tools',
    level: 95,
    levelLabel: 'Expert',
    iconName: 'Terminal',
    description: 'My main integrated development environment configured with custom snippets, extensions, and debugging tooling.',
  },
  {
    id: 'arduino-ide',
    name: 'Arduino IDE & Embedded Hardware',
    category: 'Production & Hardware',
    level: 80,
    levelLabel: 'Proficient',
    iconName: 'Cpu',
    description: 'I program hardware microcontrollers, sensor interfaces, and automated physical computing rigs.',
  },
  {
    id: 'camera-rigging',
    name: 'Camera Rigging & Stabilizers',
    category: 'Production & Hardware',
    level: 88,
    levelLabel: 'Advanced',
    iconName: 'SlidersHorizontal',
    description: 'I configure gimbals, follow-focus rigs, external monitors, wireless audio receivers, and video transmission gear for shoots.',
  },
];
